# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Cegep_Hiver_2022\qt_interface\interface_graphique_classe.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Button_Ajouter = QtWidgets.QPushButton(self.centralwidget)
        self.Button_Ajouter.setGeometry(QtCore.QRect(310, 350, 231, 61))
        font = QtGui.QFont()
        font.setFamily("Algerian")
        font.setPointSize(11)
        self.Button_Ajouter.setFont(font)
        self.Button_Ajouter.setObjectName("Button_Ajouter")
        self.Edit_Numero_etudiant = QtWidgets.QLineEdit(self.centralwidget)
        self.Edit_Numero_etudiant.setGeometry(QtCore.QRect(310, 90, 231, 41))
        self.Edit_Numero_etudiant.setObjectName("Edit_Numero_etudiant")
        self.label_Numero = QtWidgets.QLabel(self.centralwidget)
        self.label_Numero.setGeometry(QtCore.QRect(130, 110, 181, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_Numero.setFont(font)
        self.label_Numero.setObjectName("label_Numero")
        self.label_affichage = QtWidgets.QLabel(self.centralwidget)
        self.label_affichage.setGeometry(QtCore.QRect(290, 450, 261, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_affichage.setFont(font)
        self.label_affichage.setText("")
        self.label_affichage.setObjectName("label_affichage")
        self.Edit_Nom_etudiant = QtWidgets.QLineEdit(self.centralwidget)
        self.Edit_Nom_etudiant.setGeometry(QtCore.QRect(310, 150, 231, 41))
        self.Edit_Nom_etudiant.setObjectName("Edit_Nom_etudiant")
        self.label_Nom = QtWidgets.QLabel(self.centralwidget)
        self.label_Nom.setGeometry(QtCore.QRect(130, 170, 151, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_Nom.setFont(font)
        self.label_Nom.setObjectName("label_Nom")
        self.Edit_Prenom_etudiant = QtWidgets.QLineEdit(self.centralwidget)
        self.Edit_Prenom_etudiant.setGeometry(QtCore.QRect(310, 210, 231, 41))
        self.Edit_Prenom_etudiant.setObjectName("Edit_Prenom_etudiant")
        self.label_Prenom = QtWidgets.QLabel(self.centralwidget)
        self.label_Prenom.setGeometry(QtCore.QRect(130, 230, 181, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_Prenom.setFont(font)
        self.label_Prenom.setObjectName("label_Prenom")
        self.Edit_Programme_etudiant = QtWidgets.QLineEdit(self.centralwidget)
        self.Edit_Programme_etudiant.setGeometry(QtCore.QRect(310, 270, 231, 41))
        self.Edit_Programme_etudiant.setObjectName("Edit_Programme_etudiant")
        self.label_Programme = QtWidgets.QLabel(self.centralwidget)
        self.label_Programme.setGeometry(QtCore.QRect(130, 280, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_Programme.setFont(font)
        self.label_Programme.setObjectName("label_Programme")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Button_Ajouter.setText(_translate("MainWindow", "Ajouter étudiant"))
        self.label_Numero.setText(_translate("MainWindow", "Numéro de l\'étudiant"))
        self.label_Nom.setText(_translate("MainWindow", "Nom de l\'étudiant"))
        self.label_Prenom.setText(_translate("MainWindow", "Prénom de l\'étudiant"))
        self.label_Programme.setText(_translate("MainWindow", "Programme d\'étude"))
